/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConversationItem: typeof import('./components/ConversationItem.vue')['default']
    ConversationList: typeof import('./components/ConversationList.vue')['default']
    MessageFooter: typeof import('./components/MessageFooter.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    MessageStatusIcon: typeof import('./components/MessageStatusIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextElement: typeof import('./components/TextElement.vue')['default']
    TheAvatar: typeof import('./components/TheAvatar.vue')['default']
    TheConversation: typeof import('./components/TheConversation.vue')['default']
    TheDialog: typeof import('./components/TheDialog.vue')['default']
    TheFooter: typeof import('./components/layout/TheFooter.vue')['default']
    TheHackLoadIcon: typeof import('./components/TheHackLoadIcon.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheProfile: typeof import('./components/TheProfile.vue')['default']
    TheSendBox: typeof import('./components/TheSendBox.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
  }
}
